Repository corona-warn-app/cwa-testresult-server, pull requests merged in 2020-06, with the labels that each got.

#64 fix: no nullable result from lab allowed
  src/main/java/app/coronawarn/testresult/TestResultController.java
  src/main/java/app/coronawarn/testresult/model/TestResult.java
  src/main/resources/db/changelog.yml
  src/main/resources/db/changelog/v002-revert-test-result-result-nullable.yml
  src/test/java/app/coronawarn/testresult/TestResultControllerTest.java
Labels: in progress

#75 Fix: Update the release to 1.0.1 in POM-File
  pom.xml
Labels: enhancement

#74 Fix typo(?) in architecture-overview.md
  docs/architecture-overview.md
Labels: documentation
